### ISSUE TITLE
I'm seeing the wrong scores...

### ISSUE THREAD

**Issue by tolland** [cedricblondeau/world-cup-2018-cli-dashboard#16]
I just installed the app, and it looks pretty cool. But I'm seeing the wrong scores...

$ npm -v
5.6.0
$ node -v
v8.11.3
$ cat /etc/fedora-release
Fedora release 28 (Twenty Eight)

![screenshot_2018-06-25_15-34-02](https://user-images.githubusercontent.com/91288/41856555-4a810968-788d-11e8-8d5c-9835e1ad7c89.png)
![screenshot_2018-06-25_15-33-48](https://user-images.githubusercontent.com/91288/41856557-4aa50d0e-788d-11e8-933d-32f08252626d.png)

**Comment by cedricblondeau** [comment]
Yep, I just noticed this, that's an API issue 😢. That API has been just awesome so far and it will probably be fixed soon.

See: https://github.com/estiens/world_cup_json/issues/123

**Comment by cedricblondeau** [comment]
API has been fixed  🎉 

Contributors behind that API are just awesome.
