### ISSUE TITLE
Group standings do not autoupdate

### ISSUE THREAD

**Issue by MHohenberg** [cedricblondeau/world-cup-2018-cli-dashboard#18]
... they will only update after a restart.

**Comment by cedricblondeau** [comment]
They do not.

Adding a `setInterval` statement to update groups should do it but that should probably not be done each 30 seconds.

https://github.com/cedricblondeau/world-cup-2018-cli-dashboard/blob/master/src/components/Dashboard/Dashboard.jsx#L41

**Comment by cedricblondeau** [comment]
That feature has been added and released in 1.1.0.  🎉
