### ISSUE TITLE
Scrolling past last match in top row, highlighted match is hidden

### ISSUE THREAD

**Issue by lucymhdavies** [cedricblondeau/world-cup-2018-cli-dashboard#22]
https://asciinema.org/a/iAJVnecmV0XViZUPgXGKHqB2M

Pressing left and right to view past matches seems to work okay.

Would be nice if it scrolled once I got to the end of the row though.

**Comment by cedricblondeau** [comment]
I agree that would be awesome.

**Comment by cedricblondeau** [comment]
I'm currently working on a PR that will add this.

![match-nav-carousel](https://user-images.githubusercontent.com/1479924/42176815-44067436-7df8-11e8-9bdc-dd47a2d2164e.gif)
