### ISSUE TITLE
Compatibility for macOS Terminal

### ISSUE THREAD

**Issue by psomdeb25** [cedricblondeau/world-cup-2018-cli-dashboard#36]
Hello, I would like to know if this could also be used on the macOS Terminal, and how would you recommend installing it?

Thank you.

**Comment by cedricblondeau** [comment]
Hello -- It could totally be used in macOS Terminal. I personally use iTerm2 tho.

The recommended way to install it would be to use Docker. Docker makes things portable and avoid hassle of installing and managing NodeJS versions.

Installing docker and executing this should be enough:
```
docker run -ti -e TZ=America/Vancouver -e WITH_EMOJIS=0 cedricbl/world-cup-2018-cli-dashboard
```
