### ISSUE TITLE
No such file or directory: 'global'

### ISSUE THREAD

**Issue by avlima** [cedricblondeau/world-cup-2018-cli-dashboard#4]
$ yarn global add world-cup-cli-dashboard
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'global'

**Comment by cedricblondeau** [comment]
I'm wondering if this is using the right `yarn` (https://yarnpkg.com/lang/en/).

FWIW, `npm` can be used too:

```
npm install -g world-cup-cli-dashboard
```

I'll update the README with npm soon.

**Comment by cedricblondeau** [comment]
I added `npm` instructions to the README file.
